export { default as uRequest } from './uRequest';
import * as _utils from './utils';
export { _utils as utils };
import * as _utilsRequest from './uRequest';
export { _utilsRequest as utilsRequest };
export { default as request } from './request';
export { default as useDialog } from './useDialog';
export { default as useModal } from './useModal';
export { default as useOnFatherClick } from './useOnFatherClick';
export { default as getGlobalVariable } from './getGlobalVariable';
export { default as setGlobalVariable } from './setGlobalVariable';
